repos:
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.39.0
  hooks:
  - id: markdownlint
    exclude: ^docs/user-guide/
    args:
    - --fix

# Does it work on m1?
#- repo: https://github.com/gitleaks/gitleaks
#  rev: v8.18.2
#  hooks:
#    - id: gitleaks
