site_name: User documentation

nav:
    - Home:
      - index.md
      - Quick Start:
        - user-guide/quick-start/index.md
        - Data in the User Interface:
          - Data Consumer: user-guide/quick-start/consumer-gui.md
          - Data Contributor: user-guide/quick-start/contributor-gui.md
          - Administrator: user-guide/quick-start/admin-gui.md
        - Data in API:
          - Data Consumer: user-guide/quick-start/consumer-api.md
          - Data Contributor: user-guide/quick-start/contributor-api.md
          - Administrator: user-guide/quick-start/admin-gui.md
      - Key Concepts: user-guide/key-concepts/key-concepts.md
      - Users, Roles, Permissions: user-guide/users-roles-permissions/users-roles-permissions.md
      - Guides:
            - User Interface Guide:
                - user-guide/index.md
            - API Guide: user-guide/doc-odm-user-guide/quickstart_user.md
      - About Genestack: https://genestack.com/
    - Guide:
        - user-guide/index.md
        - Quick Start Guide: user-guide/doc-odm-user-guide/quickstart_user.md
        - User Setup: user-guide/doc-odm-user-guide/setup.md
        - Create New Study: user-guide/doc-odm-user-guide/create-study.md
        - Import Data on ODM: user-guide/doc-odm-user-guide/import-samples-spreadsheet.md
        - Import Data Using API: user-guide/doc-odm-user-guide/import-data-using-api.md
        - Import Data Using Python Script: user-guide/doc-odm-user-guide/import-data-using-python-script.md
        - Exporting Data: user-guide/doc-odm-user-guide/exporting-data.md
        - Cross-reference Mapping: user-guide/doc-odm-user-guide/xref-mapping.md
        - Study Browser: user-guide/doc-odm-user-guide/studybrowser.md
        - Metadata Editor: user-guide/doc-odm-user-guide/metadata-editor.md
        - Template Editor: user-guide/doc-odm-user-guide/template-editor.md
        - Curator Guide: user-guide/doc-odm-user-guide/curator_guide.md
        - Metadata Versioning: user-guide/doc-odm-user-guide/versioning.md
        - Sharing Studies: user-guide/doc-odm-user-guide/sharing.md
        - Getting a Genestack API token: user-guide/doc-odm-user-guide/getting-a-genestack-api-token.md
        - Supported File Formats: user-guide/doc-odm-user-guide/supported-formats.md
    - Tools:
        - odm-sdk:
            - Installation: tools/odm-sdk/installation.md
            - Configuration: tools/odm-sdk/configuration.md
            #- Work from python:
            - Work from terminal:
                  - Users:
                        - Users creation: tools/odm-sdk/terminal/users/user-creation.md
                  - Templates:
                        - Create or update template: tools/odm-sdk/terminal/templates/create-or-update-template.md
                        - Delete template: tools/odm-sdk/terminal/templates/delete-template.md
                  - Study:
                        - Uploading study: tools/odm-sdk/terminal/study/uploading-study.md
                        - Curation script: tools/odm-sdk/terminal/study/curation-script.md
                        - Sharing study: tools/odm-sdk/terminal/study/sharing-study.md
                        - Deleting study: tools/odm-sdk/terminal/study/deleting-study.md
                        - Loading from GEO: tools/odm-sdk/terminal/study/loading-from-geo.md
                  - Dictionaries and ontologies:
                        - Default dictionaries: tools/odm-sdk/terminal/dictionaries-and-ontologies/default-dictionaries.md
                        - Exporting ontologies from ODM: tools/odm-sdk/terminal/dictionaries-and-ontologies/exporting-ontologies-from-odm.md
                        - Creating new dictionary: tools/odm-sdk/terminal/dictionaries-and-ontologies/creating-new-dictionary.md
                        - Loading new ontology:
                              - tools/odm-sdk/terminal/dictionaries-and-ontologies/loading-new-ontology.md
                              - CSV dictionary format: tools/odm-sdk/terminal/dictionaries-and-ontologies/loading-new-ontology/csv-dictionary-format.md
                              - SKOS dictionary: tools/odm-sdk/terminal/dictionaries-and-ontologies/loading-new-ontology/skos-dictionary.md
            - Generated:
                  - tools/odm-sdk/generated/index.md
        - odm-api:
              - Python:
                    - Installation: tools/odm-api/python/installation.md
                    - Example: tools/odm-api/python/example.md
                    - Generated:
                          - tools/odm-api/python/generated/README.md
              - R:
                    - Installation: tools/odm-api/r/installation.md
                    - Example: tools/odm-api/r/example.md
                    - Generated:
                        - tools/odm-api/r/generated/README.md
    - UI:
        - Training Materials: ui/training-materials.md
    - Release notes:
          - v1.50 - v1.59: release-notes/v1.50-v1.59.md
          - v1.40 - v1.49: release-notes/v1.40-v1.49.md
          - v1.30 - v1.39: release-notes/v1.30-v1.39.md
          - v1.20 - v1.29: release-notes/v1.20-v1.29.md
theme:
    name: material
    palette:
      - scheme: default
        primary: custom
        accent: custom
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - scheme: slate
        primary: custom
        accent: custom
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
    logo: assets/logo.svg
    favicon: assets/favicon.ico
    features:
        - announce.dismiss
        - content.action.edit
        - content.action.view
        - content.code.annotate
        - content.code.copy
        # - content.code.select
        # - content.tabs.link
        - content.tooltips
        # - header.autohide
        # - navigation.expand
        - navigation.footer
        - navigation.indexes
        # - navigation.instant
        # - navigation.instant.prefetch
        # - navigation.instant.progress
        # - navigation.prune
        - navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
        # - toc.integrate
extra:
    version:
        provider: mike
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - md_in_html
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.tabbed:
          alternate_style: true
    - tables
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - codehilite
    - pymdownx.tabbed
    - toc:
        permalink: true
