name: Pre-commit

on:
  pull_request:
    branches: [develop]

jobs:
  pre-commit:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5.0.1
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
      - uses: pre-commit/action@v3.0.1
